on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: sudo apt-get install -y libostree-dev
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: sudo apt-get install -y libostree-dev
      - uses: actions-rs/cargo@v1
        with:
          command: test

  end-to-end:
    name: End-to-end upload test
    runs-on: ubuntu-22.04
    steps:
     - uses: actions/checkout@v2

     - name: Start containers
       working-directory: ./tests
       run: docker compose up -d

     - name: Wait for the containers to finish loading
       run: sleep 10

     - name: Run test
       working-directory: ./tests
       run: docker compose exec flat-manager ./tests/run-test.py

  fmt:
    name: Rustfmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Install dependencies
        run: sudo apt-get install -y libostree-dev
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings